#!/bin/bash

function __tmux_lib_main() {
  function tmux_botright() {
    local path="$(tmux display-message -p "#{pane_current_path}")"
    git --git-dir="$path/.git" rev-parse --abbrev-ref HEAD
    if git --git-dir="$path/.git" rev-parse --is-inside-work-tree > /dev/null; then
      git --git-dir="$path" rev-parse --abbrev-ref HEAD
    elif hg root > /dev/null 2>&1; then
      hg log -r . -l 1 -T tmux
    else
      echo "Terminal loves you."
    fi
  }

  function session_scrollback() {
    tmux list-windows -F '#{window_id}' | \
      xargs -n 1 tmux list-panes -F '#{pane_id}' -t | \
      xargs -n 1 tmux capture-pane -p -t
  }

  function _echo_file_if_exists() {
    while read -r maybe_file; do
      if [[ ! -f "${maybe_file%%:*}" ]]; then
        continue
      fi
      if [[ "$maybe_file" == *:* ]]; then
        echo "$maybe_file"
      else
        echo "$maybe_file:0"
      fi
    done
  }

  function session_files() {
    session_scrollback | \
      grep -Eo "[A-Za-z0-9\._\-\/:]+" | \
      sed "s|~|$HOME|g" | \
      _echo_file_if_exists | \
      awk '!seen[$0]++' # Keep unique output.
  }

  function session_scrollback_actions() {
    session_scrollback | \
      tr -d '\n' | \
      grep -Po 'add_dep\s+(("[^"]+")+\s)+[A-Za-z0-9\._\-\/]+' | \
      awk '!seen[$0]++' # Keep unique output.
  }

  case $1 in
    'session_scrollback')
      session_scrollback
      ;;

    'session_scrollback_actions')
      session_scrollback_actions
      ;;

    'session_files')
      session_files
      ;;

    'botright')
      tmux_botright
      ;;

    *)
      echo 'Invalid command! Supply session_scrollback, session_files, session_scrollback_actions, or botright'
      ;;
  esac
}

# If we're not being sourced by .bashrc, run main and exit.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  __tmux_lib_main "$@"
  exit $?
fi

# c-g to find scrollback actions
function __fzf_scrollback_actions() {
  tmux_lib session_scrollback_actions | fzf
}
bind -m emacs-standard '"\C-g": " \e[D\C-k \C-u`__fzf_scrollback_actions`\e\C-e\er\C-a\C-y\C-h\C-e\e \C-y\ey\C-x\C-x\C-f"'
bind -m vi-command '"\C-g": "\C-z\C-g\C-z"'
bind -m vi-insert '"\C-g": "\C-z\C-g\C-z"'
